<div class="alert alert-block alert-info" style="margin-top: 20px">
 <a href="http://cocl.us/pytorch_link_top"><img src = "http://cocl.us/Pytorch_top" width = 950, align = "center"></a>

<img src = "https://ibm.box.com/shared/static/ugcqz6ohbvff804xp84y4kqnvvk3bq1g.png" width = 200, align = "center">



<h1 align=center><font size = 5>Linear Regression with Multiple Outputs </font></h1> 


# Table of Contents
In this lab, we will  review how to make a prediction for Linear Regression with Multiple Output. 

<div class="alert alert-block alert-info" style="margin-top: 20px">

<li><a href="#ref2">Build Custom Modules </a></li>

<br>
<p></p>
Estimated Time Needed: <strong>15 min</strong>
</div>

<hr>

<a id="ref1"></a>
<h2 align=center>Class Linear  </h2>


In [1]:
from torch import nn
import torch

In [2]:
#Set the random seed:

In [3]:
torch.manual_seed(1)

Set the random seed:

In [4]:
class linear_regression(nn.Module):
    def __init__(self,input_size,output_size):
        super(linear_regression,self).__init__()
        self.linear=nn.Linear(input_size,output_size)
    def forward(self,x):
        yhat=self.linear(x)
        return yhat

create a linear regression  object, as our input and output will be two we set the parameters accordingly 

In [5]:
model=linear_regression(2,2)

we can use the diagram to represent the model or object 

<img src = "https://ibm.box.com/shared/static/icmwnxru7nytlhnq5x486rffea9ncpk7.png" width = 600, align = "center">

we can see the parameters 

In [6]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3643, -0.3121],
         [-0.1371,  0.3319]], requires_grad=True), Parameter containing:
 tensor([-0.6657,  0.4241], requires_grad=True)]

we can create a tensor with two rows representing one sample of data

In [8]:
x=torch.tensor([[1.0,3.0]])

we can make a prediction 

In [13]:
yhat=model(x)
yhat


tensor([[-1.2377,  1.2827]], grad_fn=<ThAddmmBackward>)

In [14]:
yhat.shape

torch.Size([1, 2])

each row in the following tensor represents a different sample 

In [10]:
X=torch.tensor([[1.0,1.0],[1.0,2.0],[1.0,3.0]])

we can make a prediction using multiple samples 

In [11]:
Yhat=model(X)
Yhat

tensor([[-0.6135,  0.6189],
        [-0.9256,  0.9508],
        [-1.2377,  1.2827]], grad_fn=<ThAddmmBackward>)

the following figure represents the operation, where the red and blue  represents the different parameters, and the different shades of green represent  different samples.

 <img src = "https://ibm.box.com/shared/static/768cul6pj8hc93uh9ujpajihnp8xdukx.png" width = 600, align = "center">

<div class="alert alert-block alert-info" style="margin-top: 20px">
 <a href="http://cocl.us/pytorch_link_bottom"><img src = "http://cocl.us/pytorch_image_bottom" width = 950, align = "center"></a>

# About the Authors:  

 [Joseph Santarcangelo]( https://www.linkedin.com/in/joseph-s-50398b136/) has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.
 
Other contributors: [Michelle Carey](  https://www.linkedin.com/in/michelleccarey/) 


 <hr>
Copyright &copy; 2018 [cognitiveclass.ai](cognitiveclass.ai?utm_source=bducopyrightlink&utm_medium=dswb&utm_campaign=bdu). This notebook and its source code are released under the terms of the [MIT License](https://bigdatauniversity.com/mit-license/).