<div class="alert alert-block alert-info" style="margin-top: 20px">
 <a href="http://cocl.us/pytorch_link_top"><img src = "http://cocl.us/Pytorch_top" width = 950, align = "center"></a>

<img src = "https://ibm.box.com/shared/static/ugcqz6ohbvff804xp84y4kqnvvk3bq1g.png" width = 200, align = "center">



<h1 align=center><font size = 5>Multiple Linear Regression</font></h1> 

In this lab, you will review how to make a prediction in several different ways by using Pytorch. 
# Table of Contents
In this lab, you will review how to make a prediction in several different ways by using Pytorch. 

<div class="alert alert-block alert-info" style="margin-top: 20px">
<li><a href="#ref0">Prediction</a></li>
<li><a href="#ref1">Class Linear</a></li>
<li><a href="#ref2">Build Custom Modules</a></li>

<br>
<p></p>
Estimated Time Needed: <strong>15 min</strong>
</div>

<hr>

In [1]:
from torch import nn
import torch


Set the random seed:

In [2]:
torch.manual_seed(1)

In [3]:
w=torch.tensor([[ 2.0],[3.0]],requires_grad=True)
b=torch.tensor([ [1.0]],requires_grad=True)


Define the parameters. <code>torch.mm</code> uses matrix multiplication instead of scaler multiplication.

In [4]:
def forward(x):
    yhat=torch.mm(x,w)+b
    return yhat

The function <code>forward</code> implements the following equation:

<img src = "https://ibm.box.com/shared/static/3tnp365tjlyz6rz61v9rmtoy52apm1t6.png" width = 600, align = "center">

Input a 1x2 tensor and get a 1x1 tensor: 

In [5]:
x=torch.tensor([[1.0,2.0]])
yhat=forward(x)
yhat

tensor([[9.]], grad_fn=<ThAddBackward>)

<img src = "https://ibm.box.com/shared/static/1azyfdjrgijjsdwx0te5x4i6870dejrw.png" width = 300, align = "center">


Each column of the following tensor represents a sample:

In [6]:
X=torch.tensor([[1.0,1.0],[1.0,2.0],[1.0,3.0]])

When you input a tensor with three rows and two columns, the function performs matrix multiplication as shown in this image:

 <img src = "https://ibm.box.com/shared/static/4mwkececqr4s9vquvzy8lh7o6fzkcpgo.png" width = 600, align = "center">


In [8]:
yhat=forward(X)
yhat

tensor([[ 6.],
        [ 9.],
        [12.]], grad_fn=<ThAddBackward>)

<a id="ref1"></a>
<h2 align=center>Class Linear  </h2>

You can use the linear class to make a prediction. You'll also use the linear class to build more complex models. Import the module:

In [9]:
model=nn.Linear(2,1)

Make a prediction with one sample:

In [10]:
yhat=model(x)
yhat

tensor([[-0.3969]], grad_fn=<ThAddmmBackward>)

Predict with multiple samples: 

In [11]:
yhat=model(X)
yhat

tensor([[-0.0848],
        [-0.3969],
        [-0.7090]], grad_fn=<ThAddmmBackward>)

<a id="ref2"></a>
<h2 align=center>Build Custom Modules </h2>

Now, you'll build a custom module. You can make more complex models by using this method later. 

In [12]:
class linear_regression(nn.Module):
    def __init__(self,input_size,output_size):
        super(linear_regression,self).__init__()
        self.linear=nn.Linear(input_size,output_size)
    def forward(self,x):
        yhat=self.linear(x)
        return yhat

Build a linear regression object. The input feature size is two. 

In [13]:
model=linear_regression(2,1)

This will input the following equation:

<img src = "https://ibm.box.com/shared/static/3tnp365tjlyz6rz61v9rmtoy52apm1t6.png" width = 600, align = "center">

You can see the randomly initialized parameters by using the <code>parameters()</code> method:

In [14]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3319, -0.6657]], requires_grad=True), Parameter containing:
 tensor([0.4241], requires_grad=True)]

You can also see the parameters by using the <code>state_dict()</code> method:

In [15]:
model.state_dict()

OrderedDict([('linear.weight', tensor([[ 0.3319, -0.6657]])),
             ('linear.bias', tensor([0.4241]))])

Input a 1x2 tensor and get a 1x1 tensor: 

In [16]:
yhat=model(x)
yhat

tensor([[-0.5754]], grad_fn=<ThAddmmBackward>)

The shape of the output is shown in the following image: 

<img src = "https://ibm.box.com/shared/static/3tnp365tjlyz6rz61v9rmtoy52apm1t6.png" width = 600, align = "center">

Make a prediction for multiple samples:

In [17]:
yhat=model(X)
yhat

tensor([[ 0.0903],
        [-0.5754],
        [-1.2411]], grad_fn=<ThAddmmBackward>)

The shape is shown in the following image: 


<img src = "https://ibm.box.com/shared/static/15g6yjiblg2qegx4eiuhmoigqbmpjbhp.png" width = 600, align = "center">

Build a model or object of type <code>linear_regression</code>. Using the <code>linear_regression</code> object will predict the following tensor: 

In [18]:
X=torch.tensor([[11.0,12.0,13,14],[11,12,13,14]])
model=linear_regression(4,1)
yhat=model(X)
yhat

tensor([[2.1062],
        [2.1062]], grad_fn=<ThAddmmBackward>)

Double-click __here__ for the solution.
<!-- Your answer is below:
model=linear_regression(4,1)
yhat=model(X)
yhat
-->

<div class="alert alert-block alert-info" style="margin-top: 20px">
 <a href="http://cocl.us/pytorch_link_bottom"><img src = "http://cocl.us/pytorch_image_bottom" width = 950, align = "center"></a>

# About the Authors:  

 [Joseph Santarcangelo]( https://www.linkedin.com/in/joseph-s-50398b136/) has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.
 
Other contributors: [Michelle Carey](  https://www.linkedin.com/in/michelleccarey/), [Mavis Zhou](  https://www.linkedin.com/in/jiahui-mavis-zhou-a4537814a/) 

<hr>

Copyright &copy; 2018 [cognitiveclass.ai](cognitiveclass.ai?utm_source=bducopyrightlink&utm_medium=dswb&utm_campaign=bdu). This notebook and its source code are released under the terms of the [MIT License](https://bigdatauniversity.com/mit-license/).